version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - SA_PASSWORD=yourStrong!Password
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  init-db:
    image: mcr.microsoft.com/mssql-tools
    container_name: sqlcmd
    depends_on:
      - db
    entrypoint: ["/bin/sh", "-c", "sleep 30 && /opt/mssql-tools/bin/sqlcmd -S db -U sa -P yourStrong!Password -i /scripts/init-db.sql"]
    volumes:
      - ./init:/scripts

volumes:
  sql_data: